# Load in NumPy

In [2]:
import numpy as np


# The basics

In [3]:
a = np.array([1,2,3], dtype = 'int16')
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


# Get Dimension

In [5]:
a.ndim

1

In [6]:
b.ndim

2

# Get shape

In [7]:
a.shape

(3,)

In [8]:
b.shape

(2, 3)

# Get type

In [9]:
a.dtype


dtype('int16')

In [10]:
b.dtype

dtype('float64')

# Get size 

In [11]:
a.itemsize

2

In [12]:
b.itemsize

8

# Get total size 

In [13]:
a.size

3

In [14]:
b.size

6

# Accessing/ changing specific elements, rows, columns  

In [42]:
c = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print (c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [16]:
# Get a specific element[r ,c]
c[0, 5]

6

In [17]:
#getting a specific row
c [0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [19]:
# Get a specific column
c [:, 2]

array([ 3, 10])

In [21]:
#Getting a little more fancy [start index: end index : stepsize]
c[0, 1: -1:2]

array([2, 4, 6])

In [22]:
c[0, 1: 6:2]

array([2, 4, 6])

In [24]:
c [1, 5] = 20
print(a)

[1 2 3]


In [27]:
b = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [29]:
#Get a specific element (work outside in)

b[0,1 ,1]

4

In [30]:
#Playing a little bit with it
b[:,1 ,:]

array([[3, 4],
       [7, 8]])

In [31]:
#replace
b[:,1,:] = [[9,9], [8,8]]

In [32]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

# Initializing different types of arrays 

In [33]:
#All 0s mtaric

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [35]:

np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [36]:

np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [37]:
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [39]:
# All 1s matrix
np.ones((4,2,2) , dtype ='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [41]:
# Any other number
np.full((2,2), 99, dtype= 'float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [44]:
# Any other number full_like
np.full_like(b , 7)


array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [46]:
# RAndom numbers

np.random.rand(4,2,3)

array([[[0.51042418, 0.93894886, 0.29392028],
        [0.83831673, 0.85280803, 0.87818699]],

       [[0.79934261, 0.59975912, 0.57414731],
        [0.53463708, 0.63253125, 0.96578507]],

       [[0.02153556, 0.32607942, 0.21478871],
        [0.88875756, 0.43525094, 0.9721655 ]],

       [[0.61754886, 0.9058553 , 0.71329795],
        [0.59929547, 0.35762342, 0.16251543]]])

In [48]:
np.random.random_sample(b.shape)

array([[[0.69426835, 0.35016365],
        [0.8196881 , 0.6343598 ]],

       [[0.54858429, 0.42608609],
        [0.53922558, 0.40238369]]])

In [50]:
#Random_desimal_numbers
np.random.rand(4,2)

array([[0.22720682, 0.56608835],
       [0.10528256, 0.33908586],
       [0.35759031, 0.98397183],
       [0.3585821 , 0.57591189]])

In [51]:
#Random integer values
np.random.randint(7, size=(3,3))

array([[6, 5, 6],
       [1, 6, 5],
       [3, 4, 6]])

In [52]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [54]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3 axis= 0)

SyntaxError: invalid syntax (<ipython-input-54-b42e196d97ca>, line 2)